import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";

export default function Home() {
  const [topUsers, setTopUsers] = useState([]);

  useEffect(() => {
    const fetchTopUsers = async () => {
      try {
        const response = await axios.get(
          "https://api.github.com/search/users",
          {
            params: {
              q: "followers:>1",
              sort: "followers",
              order: "desc",
              per_page: 5,
              page: 1,
            },
            headers: {
              Accept: "application/vnd.github.v3+json",
            },
          }
        );
        setTopUsers(response.data.items);
      } catch (error) {
        console.error("Error fetching top users:", error);
      }
    };

    fetchTopUsers();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-3">
          <h1 className="text-gray-800 font-bold text-3xl my-2 mx-1.5">
            Top 5 Github Users
          </h1>
          <p className="text-custom-gray font-roboto text-base font-normal md:mb-[40px] mb-[23px] mx-1.5">
            Tap the username to see more information
          </p>
          <ul className="flex flex-wrap">
            {topUsers.map((user) => (
              <li
                key={user.id}
                className="cursor-pointer hover:bg-blue-600 m-[5px] bg-blue-500 hover:bg-blue-700 text-white font-bold md:py-[17px] md:px-[50px] rounded py-[9px] px-[19px] text-sm md:text-base"
              >
                <Link href={`/${user.login}`}>{user.login}</Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
